language: python
python:
  - 3.6
  - 3.5

install:
  - pip install --upgrade pip
  - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'
  - pip install codecov coverage isort flake8 twine

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev

script:
 - if python -c "import sys; exit(not (sys.version >= '3.6'))"; then pip install black; black --check .; fi
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff hspatial tests
 - ./setup.py sdist bdist_wheel
 - twine check dist/*
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" ./setup.py test

after_success:
  - codecov
